root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ./cmd/proxy"
  delay = 1000
  exclude_dir = ["tmp", "vendor"]
  include_ext = ["go"]
